In [3]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids2=[[1,2,3,4,5],[1,2,2,2,2]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
shaped=tf.constant(pred_ids2,dtype=tf.int32)
# shaped=shaped.get_shape()
sliced=shaped[:,:3]
# assert tf.shape(pred_ids_t)[0]==tf.shape(shaped)[0]
# assert_op = tf.Assert(tf.less_equal(tf.reduce_max(x), 1.), [x])
equal=tf.equal(pred_ids_t,shaped)
equal_int=tf.cast(equal,dtype=tf.int32)
sum_int=tf.reduce_sum(equal_int)
size=tf.size(equal_int)
accuracy=sum_int/size
with tf.Session() as sess:
    sp=sess.run(shaped)
    print(sp)
    print(sess.run(sliced))
    print(sess.run(tf.shape(pred_ids_t)))
    print(sess.run(tf.shape(shaped)))
    print(sess.run(equal))
    print(sess.run(equal_int))
    print(sess.run(sum_int))
    print(sess.run(size))
    print(sess.run(accuracy))
#     print(sess.run(shaped))

Tensor("Sum_1:0", shape=(), dtype=int32)
[[1 2 3 4 5]
 [1 2 2 2 2]]
[[1 2 3]
 [1 2 2]]
[2 5]
[2 5]
[[ True  True  True  True  True]
 [ True  True False False False]]
[[1 1 1 1 1]
 [1 1 0 0 0]]
7
10
0.7


In [6]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
ll=[1,0,1,0]
lengths=tf.reduce_sum(ll)
sliced=tf.slice(pred_ids,[0],[lengths])
with tf.Session() as sess:
    print(sess.run(lengths))
    print(sess.run(pred_ids_t))
    print(sess.run(sliced))

ValueError: Shape must be rank 1 but is rank 2 for 'Slice_1' (op: 'Slice') with input shapes: [2,5], [1], [1].

In [9]:
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32, shape=[None])  # 1-D tensor
i = tf.reduce_sum(x)
i=tf.cast(i,dtype=tf.int32)
y = tf.slice(x, i, [1])

#initialize
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

#run
result = sess.run(y, feed_dict={x: [1, 0, 1, 0, 0], i: [0]})
print(result)

ValueError: Shape must be rank 1 but is rank 0 for 'Slice_4' (op: 'Slice') with input shapes: [?], [], [1].