In [20]:
import tensorflow as tf
import numpy as np
# Tensorflow交互式会话
tf.InteractiveSession()
aa=np.array([[1,2,3,4,5], [4,5,6,7,8], [7,8,9,10,11]])
# 定义5x5大小的一个矩阵变量
ll=[1,0,1]

lengths=tf.reduce_sum(ll)
a = tf.constant(aa, dtype=tf.float32)
ss=tf.shape(aa)
print(ss)
# 进行切片操作，起始位置为[1,1]（从0开始），大小[2,2]
b = tf.slice(a, [0, 0], [ss[0], lengths])

# # 同上
# c = tf.Variable(tf.truncated_normal(shape=[2, 6, 5], dtype=tf.float32))

# d = tf.slice(c, [0, 2, 3], [2, 3, 1])

# 全局变量初始化
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(ss))
# print("Example 02")

# print("the original matrix:\n", c.eval())

# print("after being sliced:\n", d.eval())


Tensor("Shape_6:0", shape=(2,), dtype=int32)
[[ 1.  2.  3.  4.  5.]
 [ 4.  5.  6.  7.  8.]
 [ 7.  8.  9. 10. 11.]]
[[1. 2.]
 [4. 5.]
 [7. 8.]]
[3 5]
