In [1]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids2=[[1,2,3,4,5],[1,2,2,2,2]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
shaped=tf.constant(pred_ids2,dtype=tf.int32)
# shaped=shaped.get_shape()
sliced=shaped[:,:3]
# assert tf.shape(pred_ids_t)[0]==tf.shape(shaped)[0]
# assert_op = tf.Assert(tf.less_equal(tf.reduce_max(x), 1.), [x])
equal=tf.equal(pred_ids_t,shaped)
equal_int=tf.cast(equal,dtype=tf.int32)
sum_int=tf.reduce_sum(equal_int)
size=tf.size(equal_int)
accuracy=1.0*sum_int/size
with tf.Session() as sess:
    sp=sess.run(shaped)
    print(sp)
    print(sess.run(sliced))
    print(sess.run(tf.shape(pred_ids_t)))
    print(sess.run(tf.shape(shaped)))
    print(sess.run(equal))
    print(sess.run(equal_int))
    print(sess.run(sum_int))
    print(sess.run(size))
    print(sess.run(accuracy))
#     print(sess.run(shaped))

TypeError: Expected int32, got 1.0 of type 'float' instead.

In [2]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
ll=[1,0,1,0]
lengths=tf.reduce_sum(ll)#不能使用 ,reduction_indices=1
pred_shape=tf.shape(pred_ids)
sliced=tf.slice(pred_ids,[0,0],[pred_shape[0],lengths])
with tf.Session() as sess:
    print(sess.run(lengths))
    print(sess.run(pred_ids_t))
    print(sess.run(sliced))

2
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2]
 [1 2]]


In [6]:
from tensorflow.python.ops import math_ops
from tensorflow.python.framework import constant_op
matrix=[[1],[2],[3],[4],[5]]
matrix_t=tf.constant(matrix,dtype=tf.int32)
m_t=matrix_t-1
sequence_length_less_one = math_ops.maximum(
        constant_op.constant(0, dtype=matrix_t.dtype),
        matrix_t - 1)
with tf.Session() as sess:
    print(sess.run(sequence_length_less_one))

[[0]
 [1]
 [2]
 [3]
 [4]]
