In [3]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids2=[[1,2,3,4,5],[1,2,2,2,2]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
shaped=tf.constant(pred_ids2,dtype=tf.int32)
# shaped=shaped.get_shape()
sliced=shaped[:,:3]
# assert tf.shape(pred_ids_t)[0]==tf.shape(shaped)[0]
# assert_op = tf.Assert(tf.less_equal(tf.reduce_max(x), 1.), [x])
equal=tf.equal(pred_ids_t,shaped)
equal_int=tf.cast(equal,dtype=tf.int32)
sum_int=tf.reduce_sum(equal_int)
size=tf.size(equal_int)
accuracy=sum_int/size
with tf.Session() as sess:
    sp=sess.run(shaped)
    print(sp)
    print(sess.run(sliced))
    print(sess.run(tf.shape(pred_ids_t)))
    print(sess.run(tf.shape(shaped)))
    print(sess.run(equal))
    print(sess.run(equal_int))
    print(sess.run(sum_int))
    print(sess.run(size))
    acu=sess.run(accuracy)
    print('accuracy: %s'%(acu))
#     print(sess.run(shaped))

[[1 2 3 4 5]
 [1 2 2 2 2]]
[[1 2 3]
 [1 2 2]]
[2 5]
[2 5]
[[ True  True  True  True  True]
 [ True  True False False False]]
[[1 1 1 1 1]
 [1 1 0 0 0]]
7
10
accuracy: 0.7


In [2]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
ll=[1,0,1,0]
lengths=tf.reduce_sum(ll)#不能使用 ,reduction_indices=1
pred_shape=tf.shape(pred_ids)
sliced=tf.slice(pred_ids,[0,0],[pred_shape[0],lengths])
with tf.Session() as sess:
    print(sess.run(lengths))
    print(sess.run(pred_ids_t))
    print(sess.run(sliced))

2
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2]
 [1 2]]


In [6]:
from tensorflow.python.ops import math_ops
from tensorflow.python.framework import constant_op
matrix=[[1],[2],[3],[4],[5]]
matrix_t=tf.constant(matrix,dtype=tf.int32)
m_t=matrix_t-1
sequence_length_less_one = math_ops.maximum(
        constant_op.constant(0, dtype=matrix_t.dtype),
        matrix_t - 1)
with tf.Session() as sess:
    print(sess.run(sequence_length_less_one))

[[0]
 [1]
 [2]
 [3]
 [4]]


In [5]:
logits = [[0.1, 0.5, 0.4],
          [0.8, 0.1, 0.1],
          [0.6, 0.3, 0.2]]
labels = [[0, 1, 0],
          [1, 0, 0],
          [0, 0, 1]]
acc, acc_op = tf.metrics.accuracy(labels=tf.argmax(labels, 1), 
                                  predictions=tf.argmax(logits,1))
with tf.Session() as sess:
    print(sess.run([acc, acc_op]))
    print(sess.run([acc]))

FailedPreconditionError: Attempting to use uninitialized value accuracy_1/total
	 [[node accuracy_1/total/read (defined at <ipython-input-5-6dfffa27a4d9>:8) ]]

Caused by op 'accuracy_1/total/read', defined at:
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python36\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\python36\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python36\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "c:\python36\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "c:\python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "c:\python36\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "c:\python36\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\python36\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "c:\python36\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "c:\python36\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "c:\python36\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "c:\python36\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "c:\python36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\python36\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "c:\python36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\python36\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "c:\python36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\python36\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\python36\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "c:\python36\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6dfffa27a4d9>", line 8, in <module>
    predictions=tf.argmax(logits,1))
  File "c:\python36\lib\site-packages\tensorflow\python\ops\metrics_impl.py", line 457, in accuracy
    name or 'accuracy')
  File "c:\python36\lib\site-packages\tensorflow\python\ops\metrics_impl.py", line 365, in mean
    total = metric_variable([], dtypes.float32, name='total')
  File "c:\python36\lib\site-packages\tensorflow\python\ops\metrics_impl.py", line 85, in metric_variable
    name=name)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2495, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variables.py", line 1395, in __init__
    constraint=constraint)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\variables.py", line 1557, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "c:\python36\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 81, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "c:\python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4537, in identity
    "Identity", input=input, name=name)
  File "c:\python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "c:\python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "c:\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "c:\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value accuracy_1/total
	 [[node accuracy_1/total/read (defined at <ipython-input-5-6dfffa27a4d9>:8) ]]
