In [23]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids2=[[1,2,3,4,5],[1,2,2,2,2]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
shaped=tf.constant(pred_ids2,dtype=tf.int32)
# shaped=shaped.get_shape()
sliced=shaped[:,:3]
# assert tf.shape(pred_ids_t)[0]==tf.shape(shaped)[0]
# assert_op = tf.Assert(tf.less_equal(tf.reduce_max(x), 1.), [x])
equal=tf.equal(pred_ids_t,shaped)
equal_int=tf.cast(equal,dtype=tf.int32)
sum_int=tf.reduce_sum(equal_int)
size=tf.size(equal_int)
accuracy=sum_int/size
with tf.Session() as sess:
    sp=sess.run(shaped)
    print(sp)
    print(sess.run(sliced))
    print(sess.run(tf.shape(pred_ids_t)))
    print(sess.run(tf.shape(shaped)))
    print(sess.run(equal))
    print(sess.run(equal_int))
    print(sess.run(sum_int))
    print(sess.run(size))
    print(sess.run(accuracy))
#     print(sess.run(shaped))

[[1 2 3 4 5]
 [1 2 2 2 2]]
[[1 2 3]
 [1 2 2]]
[2 5]
[2 5]
[[ True  True  True  True  True]
 [ True  True False False False]]
[[1 1 1 1 1]
 [1 1 0 0 0]]
7
10
0.7
