In [3]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids2=[[1,2,3,4,5],[1,2,2,2,2]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
shaped=tf.constant(pred_ids2,dtype=tf.int32)
# shaped=shaped.get_shape()
sliced=shaped[:,:3]
# assert tf.shape(pred_ids_t)[0]==tf.shape(shaped)[0]
# assert_op = tf.Assert(tf.less_equal(tf.reduce_max(x), 1.), [x])
equal=tf.equal(pred_ids_t,shaped)
equal_int=tf.cast(equal,dtype=tf.int32)
sum_int=tf.reduce_sum(equal_int)
size=tf.size(equal_int)
accuracy=sum_int/size
with tf.Session() as sess:
    sp=sess.run(shaped)
    print(sp)
    print(sess.run(sliced))
    print(sess.run(tf.shape(pred_ids_t)))
    print(sess.run(tf.shape(shaped)))
    print(sess.run(equal))
    print(sess.run(equal_int))
    print(sess.run(sum_int))
    print(sess.run(size))
    acu=sess.run(accuracy)
    print('accuracy: %s'%(acu))
#     print(sess.run(shaped))

[[1 2 3 4 5]
 [1 2 2 2 2]]
[[1 2 3]
 [1 2 2]]
[2 5]
[2 5]
[[ True  True  True  True  True]
 [ True  True False False False]]
[[1 1 1 1 1]
 [1 1 0 0 0]]
7
10
accuracy: 0.7


In [2]:
import tensorflow as tf
pred_ids=[[1,2,3,4,5],[1,2,3,4,5]]
pred_ids_t=tf.constant(pred_ids,dtype=tf.int32)
ll=[1,0,1,0]
lengths=tf.reduce_sum(ll)#不能使用 ,reduction_indices=1
pred_shape=tf.shape(pred_ids)
sliced=tf.slice(pred_ids,[0,0],[pred_shape[0],lengths])
with tf.Session() as sess:
    print(sess.run(lengths))
    print(sess.run(pred_ids_t))
    print(sess.run(sliced))

2
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2]
 [1 2]]


In [6]:
from tensorflow.python.ops import math_ops
from tensorflow.python.framework import constant_op
matrix=[[1],[2],[3],[4],[5]]
matrix_t=tf.constant(matrix,dtype=tf.int32)
m_t=matrix_t-1
sequence_length_less_one = math_ops.maximum(
        constant_op.constant(0, dtype=matrix_t.dtype),
        matrix_t - 1)
with tf.Session() as sess:
    print(sess.run(sequence_length_less_one))

[[0]
 [1]
 [2]
 [3]
 [4]]


In [9]:
logits = [[0.1, 0.5, 0.4],
          [0.8, 0.1, 0.1],
          [0.6, 0.3, 0.2]]
labels = [[0, 1, 0],
          [1, 0, 0],
          [0, 0, 1]]
acc, acc_op = tf.metrics.accuracy(labels=tf.argmax(labels, 1), 
                                  predictions=tf.argmax(logits,1))
sess = tf.Session()

sess.run(tf.local_variables_initializer())
sess.run(tf.global_variables_initializer())
print(sess.run([acc, acc_op]))
print(sess.run([acc]))

[(0.6666667, 0.6666667)]


In [ ]:
#condition test
import tensorflow as tf
def foo(c):
    
    if c:
        print('This is true')
    #heavy code here
    return 10
    else:
    print('This is false')
    #different code here
    return 0
a = tf.placeholder(tf.bool)  #placeholder for a single boolean value
b = foo(a)
sess = tf.InteractiveSession()
res = sess.run(b, feed_dict = {a: True})
sess.close()

In [18]:
import tensorflow as tf
def funca(is_training):
    x=tf.cond(tf.equal(is_training, tf.constant(True)), lambda: True, lambda: False) #左边lambda是true表达式
    if x：
        return "is_traing"
    else:
        return "evaluating"
a = tf.placeholder(tf.bool)  #placeholder for a single boolean value
# b = tf.cond(tf.equal(a, tf.constant(True)), lambda: tf.constant(10), lambda: tf.constant(0))
c = funca(a)
sess = tf.InteractiveSession()
res = sess.run(c, feed_dict = {a: True})
sess.close()
print(res)

SyntaxError: invalid character in identifier (<ipython-input-18-5d6d149b2c70>, line 4)

In [27]:
import tensorflow as tf
def foo(a,b):
#     c=tf.cond(tf.equal(c, tf.constant(True)), lambda: True, lambda: False) #左边lambda是true表达式
    return a*a,b*b

a = tf.placeholder(tf.bool)  #placeholder for a single boolean value
def fn1():
    return foo(1,2)
def fn2():
    return foo(2,3)
x,y=tf.cond(tf.equal(a, tf.constant(True)), true_fn=fn1,false_fn=fn2 )
# b=tf.cond(tf.equal(a, tf.constant(True)), lambda: True, lambda: False) #左边lambda是true表达式
sess = tf.InteractiveSession()
res1,res2 = sess.run([x,y], feed_dict = {a: False})
sess.close()
print(res1,res2)

4 9


In [7]:
import tensorflow as tf
#测试scope
def fun1(c):
    with tf.variable_scope("compute"):
        res=tf.cond(tf.equal(c, tf.constant(True)), lambda:tf.constant(5), lambda:tf.constant(10)) #左边lambda是true表达式
    return res
b=tf.placeholder(tf.bool)
a=tf.placeholder(tf.bool)
res1=fun1(a)
res2=fun1(b)
with tf.Session() as sess:
    print(sess.run([res1,res2],feed_dict={a: True,b:False}))

[5, 10]


In [9]:
import tensorflow as tf
with tf.variable_scope("foo") as foo_scope:
    v = tf.get_variable("v", [1])
with tf.variable_scope(foo_scope)
    w = tf.get_variable("w", [1])
with tf.variable_scope(foo_scope, reuse=True)
    v1 = tf.get_variable("v", [1])
    w1 = tf.get_variable("w", [1])
assert v1 == v
assert w1 == w

SyntaxError: invalid syntax (<ipython-input-9-57baecfcecac>, line 4)

In [2]:
import tensorflow as tf
with tf.variable_scope('foo', reuse=True):
    with tf.variable_scope('fooo', reuse=True):
        v1 = tf.get_variable('v',[1])
with tf.Session() as sess:
    print(sess.run(v1))


ValueError: Variable foo/fooo/v does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?